//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzTvix.Theme {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Default {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Default() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EzTvix.Theme.Default", typeof(Default).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Alpha {
            get {
                object obj = ResourceManager.GetObject("Alpha", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Audio {
            get {
                object obj = ResourceManager.GetObject("Audio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AudioBox {
            get {
                object obj = ResourceManager.GetObject("AudioBox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Audiocover {
            get {
                object obj = ResourceManager.GetObject("Audiocover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Background {
            get {
                object obj = ResourceManager.GetObject("Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BackgroundEmpty {
            get {
                object obj = ResourceManager.GetObject("BackgroundEmpty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BackgroundVideo {
            get {
                object obj = ResourceManager.GetObject("BackgroundVideo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Theme name=&quot;Default&quot;&gt;
        ///  &lt;Item name=&quot;Background&quot;&gt;
        ///    &lt;Text family=&quot;Segoe UI&quot; size=&quot;20&quot; bold=&quot;False&quot; italic=&quot;False&quot; color=&quot;White&quot; /&gt;
        ///    &lt;TextZone x=&quot;0&quot; y=&quot;0&quot; width=&quot;0&quot; height=&quot;0&quot; /&gt;
        ///  &lt;/Item&gt;
        ///  &lt;Item name=&quot;VideoBox&quot;&gt;
        ///    &lt;Mask x=&quot;0&quot; y=&quot;0&quot; width=&quot;200&quot; height=&quot;200&quot; /&gt;
        ///    &lt;Text family=&quot;Segoe UI&quot; size=&quot;20&quot; bold=&quot;False&quot; italic=&quot;False&quot; color=&quot;White&quot; /&gt;
        ///    &lt;TextZone x=&quot;0&quot; y=&quot;0&quot; width=&quot;0&quot; height=&quot;0&quot; /&gt;
        ///  &lt;/Item&gt;
        ///  &lt;Item name=&quot;AudioBox&quot;&gt;
        ///    &lt;Mask x=&quot;0&quot; y=&quot;0&quot; wid [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap DemoCover {
            get {
                object obj = ResourceManager.GetObject("DemoCover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Empty {
            get {
                object obj = ResourceManager.GetObject("Empty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Folder {
            get {
                object obj = ResourceManager.GetObject("Folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FolderAdventure {
            get {
                object obj = ResourceManager.GetObject("FolderAdventure", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FolderAudio {
            get {
                object obj = ResourceManager.GetObject("FolderAudio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FolderDivx {
            get {
                object obj = ResourceManager.GetObject("FolderDivx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FolderDocs {
            get {
                object obj = ResourceManager.GetObject("FolderDocs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FolderDvd {
            get {
                object obj = ResourceManager.GetObject("FolderDvd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FolderFirmware {
            get {
                object obj = ResourceManager.GetObject("FolderFirmware", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FolderHD {
            get {
                object obj = ResourceManager.GetObject("FolderHD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FolderPhoto {
            get {
                object obj = ResourceManager.GetObject("FolderPhoto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FolderSeries {
            get {
                object obj = ResourceManager.GetObject("FolderSeries", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FolderSpectacle {
            get {
                object obj = ResourceManager.GetObject("FolderSpectacle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FolderVideo {
            get {
                object obj = ResourceManager.GetObject("FolderVideo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ItemBack {
            get {
                object obj = ResourceManager.GetObject("ItemBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MovieVideoBox {
            get {
                object obj = ResourceManager.GetObject("MovieVideoBox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StarGrey {
            get {
                object obj = ResourceManager.GetObject("StarGrey", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StarYellow {
            get {
                object obj = ResourceManager.GetObject("StarYellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Theme name=&quot;Default&quot;&gt;
        ///  &lt;Item name=&quot;Background&quot;&gt;
        ///    &lt;Mask x=&quot;0&quot; y=&quot;0&quot; width=&quot;200&quot; height=&quot;200&quot; /&gt;
        ///    &lt;Text family=&quot;Segoe UI&quot; size=&quot;20&quot; bold=&quot;False&quot; italic=&quot;False&quot; color=&quot;White&quot; /&gt;
        ///    &lt;TextZone x=&quot;0&quot; y=&quot;0&quot; width=&quot;0&quot; height=&quot;0&quot; /&gt;
        ///  &lt;/Item&gt;
        ///  &lt;Item name=&quot;VideoBox&quot;&gt;
        ///    &lt;Mask x=&quot;29&quot; y=&quot;5&quot; width=&quot;142&quot; height=&quot;190&quot; /&gt;
        ///    &lt;Text family=&quot;Segoe UI&quot; size=&quot;20&quot; bold=&quot;False&quot; italic=&quot;False&quot; color=&quot;White&quot; /&gt;
        ///    &lt;TextZone x=&quot;0&quot; y=&quot;160&quot; width=&quot;200&quot; height=&quot;40&quot; /&gt;
        ///  &lt;/I [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Tvix {
            get {
                object obj = ResourceManager.GetObject("Tvix", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tvix720 {
            get {
                object obj = ResourceManager.GetObject("Tvix720", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UpFolder {
            get {
                object obj = ResourceManager.GetObject("UpFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VideoBox {
            get {
                object obj = ResourceManager.GetObject("VideoBox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VideoCover {
            get {
                object obj = ResourceManager.GetObject("VideoCover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
